# Generated by Django 5.1.7 on 2026-06-08 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('date', models.DateField(unique=True, verbose_name='fecha')),
                ('reason', models.CharField(max_length=200, verbose_name='motivo')),
                ('is_recurring', models.BooleanField(default=False, help_text='Si es un feriado fijo (ej: 25/12, 1/1) que se repite cada año', verbose_name='recurrente')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'día no laborable',
                'verbose_name_plural': 'días no laborables',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('type', models.CharField(choices=[('office', 'Consultorio'), ('nursery', 'Enfermería'), ('procedure', 'Sala de procedimientos'), ('lab', 'Laboratorio'), ('other', 'Otro')], default='office', max_length=20, verbose_name='tipo')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='ubicación')),
                ('max_capacity', models.PositiveIntegerField(default=1, verbose_name='capacidad máxima')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='día')),
                ('start_time', models.TimeField(verbose_name='hora apertura')),
                ('end_time', models.TimeField(verbose_name='hora cierre')),
                ('slot_duration', models.PositiveIntegerField(default=30, help_text='Duración del turno en minutos', verbose_name='duración turno')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='resources.resource')),
            ],
            options={
                'verbose_name': 'horario de recurso',
                'verbose_name_plural': 'horarios de recursos',
                'ordering': ['resource', 'day_of_week', 'start_time'],
            },
        ),
    ]
