# Generated by Django 5.1.7 on 2026-06-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceschedule',
            name='max_appointments_per_slot',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad máxima de turnos que pueden asignarse en esta misma ventana horaria', verbose_name='turnos máximos por ventana'),
        ),
    ]
