# Generated by Django 5.2.15 on 2026-06-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resourceschedule_max_appointments_per_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='max_appointments_per_day',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Máxima cantidad de turnos permitidos para este recurso en un mismo día. Dejar vacío para ilimitado.', null=True, verbose_name='turnos máximos por día'),
        ),
    ]
