# Generated by Django 5.1.7 on 2026-06-08 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0002_resourceschedule_max_appointments_per_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellido')),
                ('specialty', models.CharField(choices=[('general', 'Medicina General'), ('cardiology', 'Cardiología'), ('pediatrics', 'Pediatría'), ('dermatology', 'Dermatología'), ('traumatology', 'Traumatología'), ('nursing', 'Enfermería'), ('other', 'Otro')], default='general', max_length=30, verbose_name='especialidad')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='matrícula')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('resources', models.ManyToManyField(blank=True, help_text='Recursos donde este profesional puede atender', related_name='professionals', to='resources.resource', verbose_name='recursos asignados')),
            ],
            options={
                'verbose_name': 'profesional',
                'verbose_name_plural': 'profesionales',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalResourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Si se deja vacío, aplica a todos los días', null=True, verbose_name='día de semana')),
                ('start_date', models.DateField(blank=True, help_text='Si se deja vacío, la asignación es indefinida (vigente desde ahora)', null=True, verbose_name='fecha inicio')),
                ('end_date', models.DateField(blank=True, help_text='Si se deja vacío, la asignación no tiene fecha de fin', null=True, verbose_name='fecha fin')),
                ('start_time', models.TimeField(verbose_name='hora inicio')),
                ('end_time', models.TimeField(verbose_name='hora fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='professionals.professional', verbose_name='profesional')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='resources.resource', verbose_name='recurso')),
            ],
            options={
                'verbose_name': 'asignación profesional-recurso',
                'verbose_name_plural': 'asignaciones profesional-recurso',
                'ordering': ['professional', 'resource', 'day_of_week', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('professional', 'resource', 'day_of_week', 'start_time', 'end_time'), name='unique_professional_resource_slot')],
            },
        ),
    ]
