# Generated by Django 5.1.7 on 2026-06-08 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
        ('resources', '0002_resourceschedule_max_appointments_per_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('patient_name', models.CharField(max_length=200, verbose_name='nombre del paciente')),
                ('patient_dni', models.CharField(max_length=20, verbose_name='DNI del paciente')),
                ('patient_phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono de contacto')),
                ('patient_email', models.EmailField(blank=True, max_length=254, verbose_name='email de contacto')),
                ('date', models.DateField(verbose_name='fecha')),
                ('start_time', models.TimeField(verbose_name='hora inicio')),
                ('end_time', models.TimeField(verbose_name='hora fin')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('confirmed', 'Confirmado'), ('in_progress', 'En atención'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('no_show', 'No asistió')], default='scheduled', max_length=20, verbose_name='estado')),
                ('comments', models.TextField(blank=True, verbose_name='comentarios')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='professionals.professional', verbose_name='profesional')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='resources.resource', verbose_name='recurso')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date', 'resource'], name='appointment_date_d75b82_idx'), models.Index(fields=['date', 'professional'], name='appointment_date_db7516_idx'), models.Index(fields=['patient_dni'], name='appointment_patient_97e737_idx'), models.Index(fields=['status'], name='appointment_status_8fe9d7_idx')],
            },
        ),
    ]
