# Generated by Django 5.1.7 on 2026-06-09 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('professionals', '0001_initial'),
        ('resources', '0002_resourceschedule_max_appointments_per_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['resource', 'date', 'start_time'], name='appointment_resourc_41807e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['resource', 'date', 'status'], name='appointment_resourc_9c4329_idx'),
        ),
    ]
