# Generated by Django 5.1.7 on 2026-06-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_appointment_resourc_41807e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, default='', help_text='Motivo obligatorio cuando se cancela el turno', verbose_name='motivo de cancelación'),
        ),
    ]
