# Generated by Django 5.2.15 on 2026-06-10 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_cancellation_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='send_reminder',
            field=models.BooleanField(default=False, help_text='Enviar recordatorio automático antes del turno', verbose_name='enviar recordatorio'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(default='', max_length=20, verbose_name='teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programado'), ('confirmed', 'Confirmado'), ('arrived', 'Llegó'), ('in_progress', 'En atención'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('no_show', 'No asistió')], default='scheduled', max_length=20, verbose_name='estado'),
        ),
    ]
