# Generated by Django 5.2.15 on 2026-06-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_send_reminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='teléfono de contacto'),
        ),
    ]
