# Generated by Django 5.2.15 on 2026-06-14 02:55

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_patient_phone'),
        ('professionals', '0002_professional_user'),
        ('resources', '0002_resourceschedule_max_appointments_per_slot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'base_manager_name': 'all_objects', 'ordering': ['date', 'start_time'], 'verbose_name': 'turno', 'verbose_name_plural': 'turnos'},
        ),
        migrations.AlterModelManagers(
            name='appointment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='eliminado el'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['send_reminder', 'status', 'date', 'start_time'], name='idx_send_reminder_candidates'),
        ),
    ]
