# Generated by Django 5.2.15 on 2026-06-10 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_appointment_send_reminder_and_more'),
        ('resources', '0002_resourceschedule_max_appointments_per_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('reminder_enabled', models.BooleanField(default=True, verbose_name='recordatorios habilitados')),
                ('reminder_before_minutes', models.PositiveIntegerField(default=1440, help_text='Minutos antes del turno para enviar el recordatorio', verbose_name='recordar antes (minutos)')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='email habilitado')),
                ('whatsapp_enabled', models.BooleanField(default=False, verbose_name='WhatsApp habilitado')),
                ('resource', models.OneToOneField(blank=True, help_text='Dejar vacío para configuración global por defecto', null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.resource', verbose_name='recurso')),
            ],
            options={
                'verbose_name': 'configuración de notificaciones',
                'verbose_name_plural': 'configuraciones de notificaciones',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='canal')),
                ('notification_type', models.CharField(choices=[('confirmation', 'Confirmación'), ('reminder', 'Recordatorio'), ('cancellation', 'Cancelación')], max_length=20, verbose_name='tipo')),
                ('recipient', models.CharField(max_length=255, verbose_name='destinatario')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='estado')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='mensaje de error')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='appointments.appointment', verbose_name='turno')),
            ],
            options={
                'verbose_name': 'registro de notificación',
                'verbose_name_plural': 'registros de notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['appointment', 'notification_type'], name='notificatio_appoint_c4b1b2_idx'), models.Index(fields=['status'], name='notificatio_status_a242db_idx'), models.Index(fields=['created_at'], name='notificatio_created_01830a_idx')],
            },
        ),
    ]
